const API_BASE_URL = "https://dark-pine-957e.oqosfyqziob.workers.dev";
const STORAGE_KEY = "dwait_plans_v2";
const PARK_QUERY_MAP = { ランド: "land", シー: "sea", すべて: "all" };
const PARK_LABEL_MAP = { ランド: "Tokyo Disneyland", シー: "Tokyo DisneySea", すべて: "All" };
const PLAN_OPTIONS = {
  "Tokyo Disneyland": ["ディズニー・ハーモニー・イン・カラー","東京ディズニーランド・エレクトリカルパレード・ドリームライツ","Reach for the Stars","ジャンボリミッキー！レッツ・ダンス！","ミッキーのマジカルミュージックワールド","クラブマウスビート","ミッキーのレインボー・ルアウ","ザ・ダイヤモンド・バラエティマスター","レストラン予約","休憩","その他"],
  "Tokyo DisneySea": ["ビリーヴ！〜シー・オブ・ドリームス〜","ジャンボリミッキー！レッツ・ダンス！","ビッグバンドビート","ドリームス・テイク・フライト","ミッキー＆フレンズのハーバーグリーティング","ダッフィー＆フレンズのワンダフル・フレンドシップ","レストラン予約","休憩","その他"],
  All: ["レストラン予約","休憩","買い物","ホテルに戻る","移動","その他"]
};
const priorityScore = { 高: 3, 中: 2, 低: 1 }, priorityClassMap = { 高: "priority-high", 中: "priority-mid", 低: "priority-low" };
const AREA_THEME = {"ファンタジーランド":"fantasy","ウエスタンランド":"western","アドベンチャーランド":"adventure","トゥモローランド":"tomorrow","トゥーンタウン":"toon","クリッターカントリー":"critter","メディテレーニアンハーバー":"mediterranean","アメリカンウォーターフロント":"waterfront","ロストリバーデルタ":"lostriver","アラビアンコースト":"arabian","マーメイドラグーン":"mermaid","ミステリアスアイランド":"mysterious","ファンタジースプリングス":"springs"};
const ATTRACTION_META = {"プーさんのハニーハント":{childFriendly:true,indoor:true,relaxing:true,shortExperience:true,gapFriendly:true,estimatedDurationMin:12,thrillLevel:"低",priority:"高"},"モンスターズ・インク ライド＆ゴーシーク！":{childFriendly:true,indoor:true,relaxing:true,shortExperience:true,gapFriendly:true,estimatedDurationMin:10,thrillLevel:"低",priority:"高"},"ジャングルクルーズ":{childFriendly:true,indoor:false,relaxing:true,shortExperience:true,gapFriendly:true,estimatedDurationMin:10,thrillLevel:"低",priority:"中"},"ホーンテッドマンション":{childFriendly:false,indoor:true,relaxing:false,shortExperience:true,gapFriendly:true,estimatedDurationMin:13,thrillLevel:"中",priority:"中"},"ビッグサンダー・マウンテン":{childFriendly:false,indoor:false,relaxing:false,shortExperience:false,gapFriendly:false,estimatedDurationMin:18,thrillLevel:"高",priority:"高"},"イッツ・ア・スモールワールド":{childFriendly:true,indoor:true,relaxing:true,shortExperience:true,gapFriendly:true,estimatedDurationMin:14,thrillLevel:"低",priority:"中"},"美女と野獣“魔法のものがたり”":{childFriendly:true,indoor:true,relaxing:false,shortExperience:false,gapFriendly:false,estimatedDurationMin:20,thrillLevel:"中",priority:"高"},"ソアリン：ファンタスティック・フライト":{childFriendly:false,indoor:true,relaxing:false,shortExperience:false,gapFriendly:false,estimatedDurationMin:22,thrillLevel:"中",priority:"高"},"タートル・トーク":{childFriendly:true,indoor:true,relaxing:true,shortExperience:true,gapFriendly:true,estimatedDurationMin:12,thrillLevel:"低",priority:"中"},"ジャンピン・ジェリーフィッシュ":{childFriendly:true,indoor:true,relaxing:true,shortExperience:true,gapFriendly:true,estimatedDurationMin:8,thrillLevel:"低",priority:"低"},"ニモ＆フレンズ・シーライダー":{childFriendly:true,indoor:true,relaxing:true,shortExperience:true,gapFriendly:true,estimatedDurationMin:11,thrillLevel:"低",priority:"中"}};
const MODE_CONFIG = {normal:{label:"通常",w:{wait:30,open:24,priority:12,child:10,indoor:8,relax:8,short:8,gap:8,thrillPenalty:-7}},family:{label:"子連れ",w:{wait:18,open:18,priority:8,child:24,indoor:14,relax:14,short:12,gap:10,thrillPenalty:-20}},efficient:{label:"効率重視",w:{wait:45,open:25,priority:14,child:4,indoor:4,relax:2,short:18,gap:8,thrillPenalty:-4}},relax:{label:"休憩向き",w:{wait:16,open:16,priority:8,child:10,indoor:24,relax:24,short:10,gap:10,thrillPenalty:-10}},gap:{label:"すき間時間",w:{wait:40,open:20,priority:8,child:12,indoor:18,relax:16,short:24,gap:26,thrillPenalty:-12}}};
const el=(id)=>document.getElementById(id);const listElement=el("attractionList"),recommendText=el("recommendText"),recommendReasons=el("recommendReasons"),recommendNextPlan=el("recommendNextPlan"),recommendTitle=el("recommendTitle"),recommendWait=el("recommendWait");
const countText=el("countText"),currentState=el("currentState"),dataNotice=el("dataNotice"),lastUpdated=el("lastUpdated"),loadingState=el("loadingState"),closureNotice=el("closureNotice"),modeHint=el("modeHint"),appRoot=el("appRoot"),debugState=el("debugState"),areaInsightList=el("areaInsightList");
const scheduleForm=el("scheduleForm"),scheduleList=el("scheduleList"),nextPlanCard=el("nextPlanCard"),planTitle=el("planTitle"),planPark=el("planPark"),planCustomTitle=el("planCustomTitle");
let currentFilter="すべて",currentSort="recommended",currentMode="normal",liveAttractions=[],plans=[];
const parkButtons=document.querySelectorAll("[data-park-filter]"),sortButtons=document.querySelectorAll("[data-sort]"),modeButtons=document.querySelectorAll("[data-mode]");
const formatTime=(d)=>new Intl.DateTimeFormat("ja-JP",{hour:"2-digit",minute:"2-digit"}).format(d);
const CLOSED_STATUS_KEYWORDS=["closed","suspend","temporaryclosure","down","休止","運営休止","一時休止","運営していません","運営終了"];
const normalizeStatusValue=(value)=>typeof value==="string"?value.toLowerCase().replace(/\s+/g,"").replace(/[_-]/g,""):null;
const isClosedStatusText=(value)=>{const normalized=normalizeStatusValue(value);return normalized?CLOSED_STATUS_KEYWORDS.some((keyword)=>normalized.includes(keyword)):false;};
// 待ち時間ソースから数値待ち時間を取り出す（不正値は null）。
function getRideWaitNumber(ride){const waitValue=ride.waitTime??ride.wait??ride.standbyTime??ride.wait_time;const waitNumber=Number(waitValue);return waitValue!=null&&Number.isFinite(waitNumber)&&waitNumber>=0?waitNumber:null;}
// 休止・確認中・稼働中の状態判定を一本化する。
function getRideStatus(ride){const statusTexts=[ride.status,ride.operatingStatus,ride.facilityStatus,ride.operationStatus].filter((value)=>typeof value==="string");const closedByFlag=ride.isOpen===false||ride.is_open===false||ride.closed===true||ride.suspended===true||ride.temporaryClosure===true;const closedByStatus=statusTexts.some((text)=>isClosedStatusText(text));if(closedByFlag||closedByStatus)return"休止";return getRideWaitNumber(ride)==null?"確認中":"稼働中";}
// カード/レコメンド向けの待ち時間ラベルを返す。
function getWaitDisplay(ride){const status=getRideStatus(ride);if(status==="休止")return"休止";const waitNumber=getRideWaitNumber(ride);return waitNumber==null?"確認中":`${waitNumber}分`;}
// 待ち時間ソート用の値を返す（休止を末尾、確認中をその手前に配置）。
function getSortableWaitTime(ride){const status=getRideStatus(ride);if(status==="休止")return Number.POSITIVE_INFINITY;const waitNumber=getRideWaitNumber(ride);return waitNumber??Number.POSITIVE_INFINITY-1;}
function syncTheme(){appRoot.classList.remove("park-theme-land","park-theme-sea","park-theme-all");appRoot.classList.add(currentFilter==="ランド"?"park-theme-land":currentFilter==="シー"?"park-theme-sea":"park-theme-all");}
function syncPlanOptions(){const park=planPark.value;planTitle.innerHTML=PLAN_OPTIONS[park].map((x)=>`<option value="${x}">${x}</option>`).join("");toggleCustomTitle();}
function toggleCustomTitle(){const isOther=planTitle.value==="その他";scheduleForm.classList.toggle("show-custom-title",isOther);planCustomTitle.required=isOther;}
// APIレスポンスのアトラクションを、表示/スコア計算用の共通形に整える。
function normalizeRide(ride,parkName){const wait=getRideWaitNumber(ride),name=(ride.nameJa&&ride.nameJa.length)?ride.nameJa:ride.englishName||ride.name||"名称未登録",meta=ATTRACTION_META[name]||{childFriendly:true,indoor:false,relaxing:false,shortExperience:false,gapFriendly:false,estimatedDurationMin:15,thrillLevel:"中",priority:"中"};const area=ride.area||ride.land||ride.port||ride.zone||"エリア情報なし";const rideSource={isOpen:ride.isOpen,is_open:ride.is_open,status:ride.status,operatingStatus:ride.operatingStatus,facilityStatus:ride.facilityStatus,operationStatus:ride.operationStatus,closed:ride.closed,suspended:ride.suspended,temporaryClosure:ride.temporaryClosure,waitTime:ride.waitTime,wait:ride.wait,standbyTime:ride.standbyTime,wait_time:ride.wait_time};const rideStatus=getRideStatus(rideSource);return{park:parkName,area,areaTheme:AREA_THEME[area]||"default",name,wait,status:rideStatus,isOpen:ride.is_open??ride.isOpen,waitTime:ride.waitTime,waitSource:rideSource,...meta};}
function getMinutesToNextPlan(){const now=new Date();const next=plans.find((p)=>{const t=new Date();const[h,m]=p.time.split(":").map(Number);t.setHours(h,m,0,0);return t>=now;});if(!next)return{next:null,minutes:null};const t=new Date();const[h,m]=next.time.split(":").map(Number);t.setHours(h,m,0,0);return{next,minutes:Math.max(0,Math.floor((t-now)/60000))};}
// 入力: 正規化済みアトラクション1件 / 出力: おすすめ順ソート用スコア（数値）。
function computeScore(item){const m=MODE_CONFIG[currentMode].w;if(item.status==="休止")return -999;const waitScore=typeof item.wait==="number"?Math.max(0,1-item.wait/120):0.04;let s=waitScore*m.wait+(item.status==="稼働中"?1:0.2)*m.open+(priorityScore[item.priority]/3)*m.priority;s+=(item.childFriendly?1:0)*m.child+(item.indoor?1:0)*m.indoor+(item.relaxing?1:0)*m.relax+(item.shortExperience?1:0)*m.short+(item.gapFriendly?1:0)*m.gap;if((currentMode==="family"||currentMode==="gap")&&item.thrillLevel==="高")s+=m.thrillPenalty;const {minutes}=getMinutesToNextPlan();if(currentMode==="gap"&&minutes!=null){const need=(item.wait??20)+(item.estimatedDurationMin??15);s+=need<=minutes?24:-30;}if(item.status==="確認中")s-=12;return s;}
// 入力: 正規化済みアトラクション1件 / 出力: おすすめ理由のラベル配列（最大3件）。
function reasons(item){const arr=[];if(typeof item.wait==="number"&&item.wait<=25)arr.push("待ち時間短め");if(item.childFriendly)arr.push("子連れ向き");if(item.indoor)arr.push("屋内");if(item.relaxing)arr.push("休憩向き");if(item.gapFriendly)arr.push("すき間時間向き");if(item.status==="稼働中")arr.push("稼働中");const {minutes}=getMinutesToNextPlan();if(minutes!=null&&((item.wait??20)+(item.estimatedDurationMin??15)<=minutes))arr.push("次の予定までに行きやすい");return arr.slice(0,3);}
// SORT状態に応じて、待ち時間順またはおすすめ順を適用する。
function applySort(items){return currentSort==="wait"?[...items].sort((a,b)=>getSortableWaitTime(a.waitSource)-getSortableWaitTime(b.waitSource)):[...items].sort((a,b)=>computeScore(b)-computeScore(a));}
function getDisplayItems(){return applySort(currentFilter==="すべて"?liveAttractions:liveAttractions.filter((x)=>x.park===currentFilter));}
function renderPlans(){const {next,minutes}=getMinutesToNextPlan();if(!plans.length){nextPlanCard.textContent="今日の予定は未登録です";scheduleList.innerHTML="";return;}nextPlanCard.textContent=next?`次の予定: ${next.time} ${next.title}（あと${minutes}分）`:"本日の予定はすべて終了しました。";scheduleList.innerHTML=plans.map((p,i)=>`<li class="schedule-item"><span class="time-pill">${p.time}</span><div><strong>${p.title}</strong><div class="schedule-main">${p.park} / ${p.category}${p.memo?` / ${p.memo}`:""}</div></div><button class="delete-button" data-delete-plan="${i}">削除</button></li>`).join("");scheduleList.querySelectorAll("[data-delete-plan]").forEach((b)=>b.addEventListener("click",()=>{plans.splice(Number(b.dataset.deletePlan),1);savePlans();render();}));}

function summarizeAreaInsights(items){
const areaMap=new Map();
items.forEach((item)=>{const key=`${item.park}__${item.area}`;if(!areaMap.has(key))areaMap.set(key,{key,park:item.park,area:item.area,areaTheme:item.areaTheme,totalOpen:0,totalClosed:0,waitItems:[],shortest:null});const row=areaMap.get(key);const status=getRideStatus(item.waitSource);if(status==="休止")row.totalClosed+=1;else row.totalOpen+=1;if(status==="稼働中"&&typeof item.wait==="number"){row.waitItems.push(item.wait);if(!row.shortest||item.wait<row.shortest.wait)row.shortest={name:item.name,wait:item.wait};}});
return [...areaMap.values()].map((row)=>{const hasWait=row.waitItems.length>0;const avgWait=hasWait?Math.round(row.waitItems.reduce((sum,w)=>sum+w,0)/row.waitItems.length):null;return{...row,avgWait,hasWait};}).sort((a,b)=>{const aRank=a.hasWait&&a.totalOpen>0?0:1;const bRank=b.hasWait&&b.totalOpen>0?0:1;if(aRank!==bRank)return aRank-bRank;if(aRank===1)return a.area.localeCompare(b.area,"ja");return a.avgWait-b.avgWait||a.area.localeCompare(b.area,"ja");});
}
// エリア洞察カードの集計結果を描画する。
function createAreaInsightCard(areaInsight){const card=document.createElement("article");card.className="area-card";const avgText=areaInsight.avgWait==null?"確認中":`平均 ${areaInsight.avgWait}分`;const shortestText=areaInsight.shortest?`最短：${areaInsight.shortest.name} ${areaInsight.shortest.wait}分`:"最短：集計対象なし";card.innerHTML=`<div class="area-card-head"><p class="area-name">${areaInsight.area}</p><p class="area-park">${PARK_LABEL_MAP[areaInsight.park]||areaInsight.park}</p></div><p class="area-avg">${avgText}</p><p class="area-count">営業中 ${areaInsight.totalOpen}件 / 休止 ${areaInsight.totalClosed}件</p><p class="area-shortest">${shortestText}</p>`;return card;}
// エリア洞察セクション全体の再描画を行う。
function renderAreaInsights(items){if(!areaInsightList)return;const areaInsights=summarizeAreaInsights(items);areaInsightList.innerHTML="";if(!areaInsights.length){areaInsightList.innerHTML='<p class="area-empty">集計対象なし</p>';return;}areaInsights.forEach((row)=>areaInsightList.appendChild(createAreaInsightCard(row)));}

function createCard(item){const waitText=getWaitDisplay(item.waitSource),waitClass=item.status==="稼働中"?"wait-running":item.status==="休止"?"wait-paused":"wait-unknown",tags=[item.childFriendly&&"子連れ向き",item.indoor&&"屋内",item.relaxing&&"休憩向き",item.shortExperience&&"待ち時間短め",item.gapFriendly&&"すき間時間"].filter(Boolean);const card=document.createElement("article");card.className="card";card.innerHTML=`<div class="card-thumb area-${item.areaTheme}" aria-hidden="true"><span></span></div><div class="card-main"><div class="card-head"><div><h3>${item.name}</h3><p class="area">${PARK_LABEL_MAP[item.park]||item.park} ・ ${item.area}</p></div><span class="wait-time ${waitClass}">${waitText}</span></div><div class="meta-row"><span class="badge ${priorityClassMap[item.priority]}">優先度 ${item.priority}</span><span class="badge status-badge">${item.status}</span><span class="badge thrill-badge">スリル ${item.thrillLevel}</span>${tags.map((t)=>`<span class="badge feature-badge">${t}</span>`).join("")}</div></div>`;return card;}
function render(){syncTheme();const items=getDisplayItems();listElement.innerHTML="";items.forEach((i)=>listElement.appendChild(createCard(i)));renderAreaInsights(items);currentState.textContent=`${PARK_LABEL_MAP[currentFilter]} / ${currentSort==="wait"?"待ち時間順":"おすすめ順"}`;modeHint.textContent=`モード: ${MODE_CONFIG[currentMode].label}`;countText.textContent=`${items.length}件`;renderPlans();const ranked=applySort(items.filter((x)=>x.status==="稼働中").length?items.filter((x)=>x.status==="稼働中"):items),top=ranked[0];if(!top){recommendTitle.textContent="現在おすすめを表示できません";recommendText.textContent="現在は判断材料が少ないため、開園中に再確認してください。";recommendWait.textContent="確認中";recommendNextPlan.textContent="";recommendReasons.innerHTML="";return;}const weak=items.length&&items.filter((x)=>x.status!=="稼働中").length/items.length>=0.8;closureNotice.textContent=weak?"現在は判断材料が少ないため、開園中に再確認してください。":"";recommendTitle.textContent=top.name;recommendText.textContent=`${PARK_LABEL_MAP[top.park]||top.park} ・ ${top.area}`;recommendWait.textContent=getWaitDisplay(top.waitSource);const {next,minutes}=getMinutesToNextPlan();recommendNextPlan.textContent=next?`次の予定: ${next.title}（あと${minutes}分）までに組み込みやすい候補です。`:"次の予定が未登録のため、短時間で回りやすい候補を優先しています。";recommendReasons.innerHTML=reasons(top).map((r)=>`<span class="badge reason-badge">${r}</span>`).join("");}
function savePlans(){localStorage.setItem(STORAGE_KEY,JSON.stringify(plans));}
function loadPlans(){try{plans=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]").filter((p)=>p?.title&&p?.time);}catch{plans=[];}plans.sort((a,b)=>a.time.localeCompare(b.time));}
async function fetchWorkerData(parkName){const url=`${API_BASE_URL.replace(/\/$/,"")}/?park=${PARK_QUERY_MAP[parkName]||"all"}`;const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error("http");const data=await response.json();if(!Array.isArray(data?.rides))throw new Error("shape");const rides=data.rides.map((r)=>normalizeRide({name:r.name,nameJa:r.nameJa,englishName:r.englishName,waitTime:r.waitTime,wait_time:r.wait_time,wait:r.wait,standbyTime:r.standbyTime,is_open:r.is_open,isOpen:r.isOpen,status:r.status,operatingStatus:r.operatingStatus,facilityStatus:r.facilityStatus,operationStatus:r.operationStatus,closed:r.closed,suspended:r.suspended,temporaryClosure:r.temporaryClosure,land:r.area},r.park));const stats={total:rides.length,waitNumber:rides.filter((r)=>typeof r.wait==="number").length,waitNullish:rides.filter((r)=>r.wait==null).length,isOpen:rides.filter((r)=>r.isOpen===true).length};return{rides,fetchedAt:data.fetchedAt||data.generated_at||null,stats};}
function updateDebug(info){if(!debugState)return;debugState.textContent=`API: ${info.apiStatus} / rides: ${info.total} / wait(number): ${info.waitNumber} / wait(nullish): ${info.waitNullish} / isOpen(true): ${info.isOpen} / data: ${info.mode}`;}
async function refreshData(){loadingState.textContent="読み込み中…";dataNotice.textContent="待ち時間データ取得中";try{const result=await fetchWorkerData(currentFilter);liveAttractions=result.rides;dataNotice.textContent="リアルタイム取得中";lastUpdated.textContent=`${formatTime(result.fetchedAt?new Date(result.fetchedAt):new Date())}（API）`;updateDebug({apiStatus:"成功",...result.stats,mode:"リアルタイム"});}catch{dataNotice.textContent="取得失敗（画面再読み込みで再試行）";lastUpdated.textContent=`${formatTime(new Date())}（失敗時刻）`;liveAttractions=[];updateDebug({apiStatus:"失敗",total:0,waitNumber:0,waitNullish:0,isOpen:0,mode:"サンプルなし"});}finally{loadingState.textContent="";render();}}
scheduleForm.addEventListener("submit",(e)=>{e.preventDefault();const selected=planTitle.value;const title=selected==="その他"?planCustomTitle.value.trim():selected;if(!title)return;plans.push({title,time:el("planTime").value,park:planPark.value,category:el("planCategory").value,memo:el("planMemo").value.trim()});plans.sort((a,b)=>a.time.localeCompare(b.time));savePlans();scheduleForm.reset();syncPlanOptions();render();});
planPark.addEventListener("change",syncPlanOptions);planTitle.addEventListener("change",toggleCustomTitle);
parkButtons.forEach((b)=>b.addEventListener("click",async()=>{currentFilter=b.dataset.parkFilter;parkButtons.forEach((x)=>x.classList.toggle("is-active",x===b));await refreshData();}));
sortButtons.forEach((b)=>b.addEventListener("click",()=>{currentSort=b.dataset.sort;sortButtons.forEach((x)=>x.classList.toggle("is-active",x===b));render();}));
modeButtons.forEach((b)=>b.addEventListener("click",()=>{currentMode=b.dataset.mode;modeButtons.forEach((x)=>x.classList.toggle("is-active",x===b));render();}));
loadPlans();syncPlanOptions();refreshData();
